---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    exclude_fingerprints:
      - da5f23e8ba9dd8b508bb7f87cdca8e58   # static access to Yaml::dump()
      - 148ace93654875a2ab09c2e2c58fed78   # static access to Yaml::parse()
ratings:
  paths:
  - "**.php"
exclude_paths:
- tests/
